const AllData = [
  {
    cardId: 1,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712554783/cosmetic/Shea%20Body%20Butter%20Body%20Lotion/2_1_wuiggd.jpg",
    brand: "",
    mrp: 1499,
    price: (1499 - Math.round((1499*10)/100)),
    title: " Shea Body Butter Body Lotion",
    size:`200 gm`,
    qty:1,
    ingredient:``,
    bullet1: `Intensely Moisturizes: Deeply hydrates your skin for a radiant, healthy-looking glow.`,
    bullet2: `Natural Goodness: Formulated with a blend of natural ingredients to nourish and protect.`,
    bullet3: `Luxurious Feel: Velvety soft texture melts effortlessly, leaving skin feeling irresistibly soft and pampered.`,
    bullet4: `Subtle Fragrance: Delicately infused with a calming, ethereal scent for a truly sensorial experience.`,
  },  
  {
    cardId: 2,
    mrp: 1799,
    price: (1799 - Math.round((1799*10)/100)),
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712554539/cosmetic/Age%20defense/5_x4zrtx.jpg",
    brand: "IskiUski",
    title: "Age Defence Serum",
    size:`30 ml`,
    qty:1,
    bullet1: `This luxurious, concentrated serum targets the visible signs of aging, revealing a more youthful and radiant you.`,
    bullet2: `Formulated with powerful ingredients to diminish the appearance of fine lines and wrinkles, promoting a smoother, firmer complexion.`,
    bullet3: `Supports your skin's natural collagen production, providing essential building blocks for a more youthful appearance.`,
    bullet4: `Improves skin elasticity, leaving your skin feeling tighter and more lifted.`,
    bullet5: `Experience the transformation power of Regal Resilience as it helps you achieve a more ageless and radiant look.`
  },
  {
    cardId: 3,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712555020/cosmetic/DAY%20Face%20CREAEM/4_lkqumv.jpg",
    brand: "IskiUski",
    mrp: 1549,
    price: (1549 - Math.round((1549*10)/100)),
    title: "Day Face cream",
    size:`100 gm`,
    qty:1,
    bullet1: `Infused with moisture-rich ingredients, this day cream delivers long-lasting hydration, leaving your skin feeling soft, supple, and comfortable throughout the day.`,
    bullet2: `Formulated with antioxidants and SPF (if applicable), it helps shield your skin from environmental aggressors and damaging UV rays, promoting a healthy, youthful appearance.`,
    bullet3: `This lightweight cream illuminates your skin, revealing a natural, radiant glow that lasts all day long.`,
    bullet4: `Enriched with a delicate rose fragrance, Roaring Beauty Day Cream creates a truly sensorial skincare experience.`,
    bullet5: ``,
  },
  {
    cardId: 4,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712555360/cosmetic/Scrub/4_hixyzj.jpg",
    brand: "IskiUski",
    mrp: 1449,
    price: (1449 - Math.round((1449*10)/100)),
    title: "Scrub",
    size:`200 gms`,
    qty:1,
    bullet1: `Experience the transformative power of Diamond Sands, a luxurious body scrub designed to reveal your skin's natural brilliance.`,
    bullet2: `Diamond Sands gently buffs away dead skin cells and impurities, promoting a smoother, more refined texture.`,
    bullet3: `As it removes dullness and roughness, this scrub reveals your skin's natural luminosity, leaving it looking radiant and healthy.`,
    bullet4: `Formulated with nourishing ingredients (mention if any - e.g., shea butter, coconut oil), Diamond Sands helps protect your skin's natural moisture barrier, leaving it feeling soft and pampered.
    `,
    bullet5: `Infused with a captivating sandalwood fragrance, Diamond Sands transforms your skincare routine into a truly sensorial experience.`,
  },
  {
    cardId: 5,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712561670/cosmetic/Skin%20radiance%20beauty%20Elixir%20Serum/4_nclq3w.jpg",
    brand: "IskiUski",
    mrp: 1849,
    price: (1849 - Math.round((1849*10)/100)),
    title: "Skin Radiance Beauty Elixir Serum",
    size: `30ml `,
    qty:1,
    bullet1: `Deep Hydration: Infused with moisture-rich ingredients (mention if any), Aurelian Elixir delivers deep hydration, leaving your skin feeling plump, supple, and comfortable.`,
    bullet2: `This potent formula helps address uneven skin tone and dullness, revealing a natural, luminous complexion.`,
    bullet3: `Formulated with antioxidants, Aurelian Elixir helps protect your skin from environmental aggressors and free radical damage, promoting a healthy, youthful appearance.
    `,
    bullet4: `As it hydrates and protects, this serum helps revitalize your skin, leaving it looking refreshed and radiant.`
  },
  {
    cardId: 6,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712555960/cosmetic/Beard%20Oil/4_i2couo.jpg",
    brand: "IskiUski",
    mrp: 1049,
    price: (1049 - Math.round((1049*10)/100)),
    size: `30 ml`,
    qty:1,
    title: "Beard Oil",
    bullet1: `Experience the transformative power of Majestic Whisker Nectar, a luxurious beard oil designed to nourish, condition, and tame your beard for a healthy, well-groomed look.`,
    bullet2: `This nourishing oil deeply hydrates and conditions your beard, leaving it feeling softer, smoother, and more manageable.`,
    bullet3: `Formulated with essential nutrients, Majestic Whisker Nectar helps promote healthy beard growth, encouraging a fuller, more luxurious look.`,
    bullet4: `This oil effectively controls flyaways and frizz, leaving your beard looking polished and perfectly groomed.`,
    bullet5: `Infused with a refreshing rosemary scent, Majestic Whisker Nectar leaves a subtle, masculine fragrance that lingers throughout the day.`

  },
  {
    cardId: 7,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712563714/cosmetic/Beard%20Balm/7_1_jmjejo.jpg",
    brand: "IskiUski",
    mrp: 749,
    price: 749,
    size:`50gm`,
    qty:1,
    title: "BEARD BALM",
    bullet1: `Craft your ideal beard with Noble Heritage Whisker Balm, a luxurious balm designed to condition, style, and enhance your facial mane.`,
    bullet2: `Nourishing ingredients infuse your beard hair with essential moisture, leaving it feeling soft, manageable, and healthy.`,
    bullet3: `This balm provides a flexible hold, allowing you to sculpt and define your beard for a polished, distinguished look.`,
    bullet4: `Formulated to enhance your beard's natural texture and shine, Noble Heritage Whisker Balm highlights your unique facial hair for a captivating presence.`,
    bullet5: `Infused with a captivating musk scent, this balm leaves a subtle, masculine fragrance that lingers throughout the day.`
  },
  {
    cardId: 8,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712563868/cosmetic/vitamin%20c/5_1_sktbsw.jpg",
    brand: "IskiUski",
    mrp: 1649,
    price: (1649 - Math.round((1649*10)/100)),
    title: "SKIN BRIGHTENING SERUM WITH VITAMIN C",
    size: `30ml`,
    qty:1,
    bullet1: `Experience the transformative power of Elixir of Brilliance, a potent serum infused with Vitamin C to revitalize your complexion and reveal a more even-toned, luminous you.`,
    bullet2: `Formulated with Vitamin C, this serum helps address the appearance of hyperpigmentation and uneven skin tone, promoting a more balanced and radiant complexion.`,
    bullet3: `As it combats dullness and unevenness, Elixir of Brilliance reveals your skin's natural luminosity, leaving it looking healthy and glowing.`,
    bullet4: `Vitamin C's antioxidant properties help protect your skin from environmental aggressors and free radical damage, promoting a youthful and revitalized appearance.`,
    bullet5:  `Infused with a refreshing natural orange scent, this serum provides a subtle, uplifting experience for your senses.`
  },
  {
    cardId: 9,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712564012/cosmetic/4_bpvzat.jpg",
    brand: "IskiUski",
    mrp: 1849,
    price: (1849 - Math.round((1849*10)/100)),
    size:` 50ml`,
    qty:1,
    title: "Night Cream",
    bullet1: `Experience the restorative power of Lioness Oasis Night Nourisher, a luxurious night cream designed to deeply hydrate, renew, and nourish your skin while you sleep, revealing a radiant morning glow.`,
    bullet2: `Infused with moisture-rich ingredients, this night cream delivers long-lasting hydration, leaving your skin feeling soft, supple, and comfortable throughout the night.`,
    bullet3: `As you rest, Lioness Oasis Night Nourisher works to renew and nourish your skin. Formulated with powerful ingredients`,
    bullet4: `Experience a visible difference in the morning. Awake to a complexion that feels refreshed, revitalized, and radiantly glowing.`,
    bullet5: `Infused with a calming blend of saffron and neroli fragrances, this night cream creates a truly sensorial and relaxing bedtime experience.`
  },
  {
    cardId: 10,
    image: "https://res.cloudinary.com/drj0uehgx/image/upload/v1712564250/cosmetic/HAIR%20ELIXER/4_ia5rwu.jpg",
    brand: "IskiUski",
    mrp: 2499,
    price: (2499 - Math.round((2499*20)/100)),
    size:`100ml`,
    qty:1,
    title: "Magic hair oil",
    bullet1: `Experience the transformative power of Royal Rejuvenation Hair Elixir, a potent blend of essential oils designed to nourish, strengthen, and restore your hair's natural brilliance.`,
    bullet2: `This luxurious elixir infuses your hair with essential nutrients, leaving it feeling deeply nourished and conditioned.`,
    bullet3: `Formulated with fortifying ingredients, Royal Rejuvenation Hair Elixir helps strengthen your hair, improving its resilience against breakage and damage.`,
    bullet4: `As it nourishes and strengthens, this elixir helps revive your hair's natural shine, leaving it looking healthy and radiant from root to tip.`,
    bullet5: `Infused with a captivating blend of essential oils (mention specific oils if known), this elixir provides a delightful aromatic experience for your senses.`
  },
];

export default AllData;
