const AllData = [
  {
    id: 1,
    productTitle: "EVIL EYE BRACELET",
    productSubtitle: "",
    category: 'bracelet',
    mrp: " 1599",
    price: " 1099 ",
    color1: " Rose Gold",
    color2: " Gold",
    color3: " Silver",
    size1: "  Apt for 2.4-2.8 hands, Diameter - 6cm",
    size2: "  ",
    size3: "  ",
    shape: " Oval",
    specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
    gemType: " Cubic Zirconia",
    itemWeight: "100gm ",
    quality: "Premium Quality",
    silverimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713925609/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3388_e7dqgz.jpg",
    silverimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713925606/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3353_qumvqv.jpg",
    roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1714036862/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3381_htn3np.jpg",
    goldimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713925234/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3387_sfhb9z.jpg",
    goldimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713866671/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3351_pxm5jc.jpg",
    mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1714036862/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3381_htn3np.jpg",
    roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1714036862/Crown-Nine/EVIL%20EYE%20BRACELET/DSC_3381_htn3np.jpg"
  },

  {
    id: 2,
    productTitle: "CARTIER BRACELET",
    productSubtitle: "",
    category: 'bracelet',
    mrp: " 1599",
    price: " 1099 ",
    color1: " Rose Gold",
    color2: " Gold",
    color3: " Silver",
    size1: "S(17)",
    size2: "M(18)",
    size3: "L(19)",
    shape: " Oval",
    specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
    gemType: " Cubic Zirconia",
    itemWeight: "100gm ",
    quality: "Premium Quality",
    silverimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713938818/Crown-Nine/CARTIER%20BRACELET/DSC_3378_j6jse9.jpg",
    silverimage2: " ",
    roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713938767/Crown-Nine/CARTIER%20BRACELET/DSC_3393_urbvws.jpg",
    roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713938769/Crown-Nine/CARTIER%20BRACELET/DSC_3347_czllgi.jpg",
    goldimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713938789/Crown-Nine/CARTIER%20BRACELET/DSC_3394_yc6hpx.jpg",
    goldimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713938781/Crown-Nine/CARTIER%20BRACELET/DSC_3346_znqiaa.jpg",
    mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713938789/Crown-Nine/CARTIER%20BRACELET/DSC_3394_yc6hpx.jpg",
  },

  {
    id: 2,
    productTitle: "BRACELET",
    productSubtitle: "",
    category: 'bracelet',
    mrp: "1199",
    price: "849",
    color1: " Rose Gold",
    color2: " Gold",
    color3: " ",
    size1: "apt for 2.4-2.8 hands, Diameter - 6cm    ",
    size2: "",
    size3: "",
    shape: " Oval",
    specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
    gemType: " Cubic Zirconia",
    itemWeight: "100gm ",
    quality: "Premium Quality",
    silverimage1: " ",
    silverimage2: " ",
    roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871457/Crown-Nine/bracelet/DSC_3376_cjjvpj.jpg",
    roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871454/Crown-Nine/bracelet/DSC_3355_vhxoeu.jpg",
    goldimage1: "",
    goldimage2: "",
    mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871457/Crown-Nine/bracelet/DSC_3376_cjjvpj.jpg",
  },

  {
    id: 3,
    productTitle: "BRACELET",
    productSubtitle: "",
    category: 'bracelet',
    mrp: "1599",
    price: "1099",
    color1: " Rose Gold",
    color2: " Gold",
    color3: " ",
    size1: "apt for 2.4-2.8 hands, Diameter - 6cm    ",
    size2: "",
    size3: "",
    shape: " Oval",
    specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
    gemType: " Cubic Zirconia",
    itemWeight: "100gm ",
    quality: "Premium Quality",
    silverimage1: " ",
    silverimage2: " ",
    roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871673/Crown-Nine/bracelet%202/DSC_3392_sw7bjj.jpg",
    roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871669/Crown-Nine/bracelet%202/DSC_3350_qvnfwh.jpg",
    goldimage1: "",
    goldimage2: "",
    mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871673/Crown-Nine/bracelet%202/DSC_3392_sw7bjj.jpg",
  },


  {
    id: 4,
    productTitle: "BRACELET",
    productSubtitle: "",
    category: 'bracelet',
    mrp: "1199",
    price: "849",
    color1: " Rose Gold",
    color2: " ",
    color3: " ",
    size1: "apt for 2.4-2.8 hands, Diameter - 6cm    ",
    size2: "",
    size3: "",
    shape: " Oval",
    specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
    gemType: " Cubic Zirconia",
    itemWeight: "100gm ",
    quality: "Premium Quality",
    silverimage1: " ",
    silverimage2: " ",
    roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871904/Crown-Nine/bracelet%203/DSC_3386_ghhvp5.jpg",
    roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871900/Crown-Nine/bracelet%203/DSC_3359_seotrj.jpg",
    goldimage1: "",
    goldimage2: "",
    mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871904/Crown-Nine/bracelet%203/DSC_3386_ghhvp5.jpg",
  },

  // images required
  // {
  //   id: 5,
  //   productTitle: "RING CUM BRACELET",
  //   productSubtitle: "",
  //   mrp: "1199",
  //   price: "849",
  //   color1: " Rose Gold",
  //   color2: " ",
  //   color3: " ",
  //   size1: "One Size, Flexible    ",
  //   size2: "",
  //   size3: "",
  //   shape: " Oval",
  //   specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
  //   gemType: " Cubic Zirconia",
  //   itemWeight: "100gm ",
  //   quality: "Premium Quality",
  //   silverimage1: " ",
  //   silverimage2: " ",
  //   roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871904/Crown-Nine/bracelet%203/DSC_3386_ghhvp5.jpg",
  //   roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871900/Crown-Nine/bracelet%203/DSC_3359_seotrj.jpg",
  //   goldimage1: "",
  //   goldimage2: "",
  //   mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871904/Crown-Nine/bracelet%203/DSC_3386_ghhvp5.jpg",
  // },

  // images required
  // {
  //   id: 6,
  //   productTitle: "TROPICAL CHARMS BRACELET",
  //   productSubtitle: "",
  //   mrp: "1199",
  //   price: "849",
  //   color1: " Gold",
  //   color2: " ",
  //   color3: " ",
  //   size1: "One Size, Flexible    ",
  //   size2: "",
  //   size3: "",
  //   shape: " ",
  //   specification: " Anti Tarnish stainless steel, Water proof, Sweat Proof, Crafted for daily use. Skin friendly and anti - alergic",
  //   gemType: " Cubic Zirconia",
  //   itemWeight: "100gm ",
  //   quality: "Premium Quality",
  //   silverimage1: " ",
  //   silverimage2: " ",
  //   roseimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871904/Crown-Nine/bracelet%203/DSC_3386_ghhvp5.jpg",
  //   roseimage2: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871900/Crown-Nine/bracelet%203/DSC_3359_seotrj.jpg",
  //   goldimage1: "",
  //   goldimage2: "",
  //   mainimage1: "https://res.cloudinary.com/dc6gh4zlc/image/upload/v1713871904/Crown-Nine/bracelet%203/DSC_3386_ghhvp5.jpg",
  // },


];

export default AllData;
